### ISSUE TITLE
Loss of goods on death with keep inventory set to on

### ISSUE THREAD

**Issue by Winddbourne** [kirderf1/InventoryFree#3]
I've been working on a Skyblock pack and since I wanted to see what would happen if somebody fell off the edge with keep inventory set to on I unlocked one slot, filled my hotbar with junk, put something into the new slot, and then jumped off the edge.

What I expected was to have my inventory locked back up with an item inside it that I couldn't access until I was able to unlock that slot again. That would have been amazing.

What actually happened is that I kept everything on my hot bar, but lost the item from that extra slot. I even paid to unlock it again and it really was empty so I know the item wasn't just hidden behind that red X.  It was gone.

I'm assuming the thing dropped to the "ground" and was lost to the void below, I haven't tested to confirm that theory though and for all I know my gear was completely destroyed. 

I consider this to be a bug in the context of skyblock maps, A lot of servers will turn on the Keep Inventory rule simply to prevent players from having their entire inventory despawn when they fall. 

Frankly I don't normally play  that way myself and even consider losing items to be a fair price for not being more careful but . . . If some server does turn the rule on I don't mind that.  So long as the stuff remains out of reach inside locked slots the player still has to do a bit of work trying to get their goods back. 

That's part of what I want this mod to do, it should make them play with a bit more care even on servers that activate easy mode.

**Comment by kirderf1** [comment]
Good point. Yeah, relocking slots on death doesn't really work well with keepInventory because of that. I could try and do something for it, but it's not a simple fix because of how the mod fundamentally works, as locked slots are enforced server-side by dropping anything that's in them (as there is no foolproof way of directly blocking off inventory slots).

I've got an idea to try and solve this by moving items in relocked slots to a separate inventory that unlike the normal player inventory is only accessible by the mod.
